In [1]:
import pandas as pd

cases = pd.read_csv("covid_confirmed_usafacts.csv")
deaths = pd.read_csv("covid_deaths_usafacts.csv")
population = pd.read_csv("covid_county_population_usafacts.csv")

In [2]:
pd.merge(cases, deaths, on='countyFIPS', how='inner')

,countyFIPS,County Name_x,State_x,StateFIPS_x,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,2023-07-14_y,2023-07-15_y,2023-07-16_y,2023-07-17_y,2023-07-18_y,2023-07-19_y,2023-07-20_y,2023-07-21_y,2023-07-22_y,2023-07-23_y
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5738,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,142,142,142,142,142,142,142,142,142,142
5739,56039,Teton County,WY,56,0,0,0,0,0,0,...,16,16,16,16,16,16,16,16,16,16
5740,56041,Uinta County,WY,56,0,0,0,0,0,0,...,43,43,43,43,43,43,43,43,43,43
5741,56043,Washakie County,WY,56,0,0,0,0,0,0,...,51,51,51,51,51,51,51,51,51,51
5742,56045,Weston County,WY,56,0,0,0,0,0,0,...,24,24,24,24,24,24,24,24,24,24

In [3]:
covid_df = pd.merge(cases, deaths, on='countyFIPS', how='inner')

In [4]:
covid_df = covid_df[covid_df['countyFIPS'] != 0]

In [5]:
super_covid_df = pd.merge(covid_df, population, on='countyFIPS', how='inner')

In [6]:
super_covid_df.to_csv("super_covid_data.csv", index=False)

In [7]:
super_covid_df.head()

,countyFIPS,County Name_x,State_x,StateFIPS_x,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,2023-07-17_y,2023-07-18_y,2023-07-19_y,2023-07-20_y,2023-07-21_y,2023-07-22_y,2023-07-23_y,County Name,State,population
0,1001,Autauga County,AL,1,0,0,0,0,0,0,...,235,235,235,235,235,235,235,Autauga County,AL,55869
1,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,731,731,731,731,731,731,731,Baldwin County,AL,223234
2,1005,Barbour County,AL,1,0,0,0,0,0,0,...,104,104,104,104,104,104,104,Barbour County,AL,24686
3,1007,Bibb County,AL,1,0,0,0,0,0,0,...,111,111,111,111,111,111,111,Bibb County,AL,22394
4,1009,Blount County,AL,1,0,0,0,0,0,0,...,261,261,261,261,261,261,261,Blount County,AL,57826

# Enrichment data

In [8]:
import pandas as pd

enrichment_df = pd.read_csv('State.DP05-2024-01-31T061845.csv')

print(enrichment_df.head())

                            Label (Grouping) Alabama!!Estimate  \
0                                SEX AND AGE               NaN
1                       Â Â Â Â Total population         4,887,871
2                               Â Â Â Â Â Â Â Â Male         2,369,271
3                             Â Â Â Â Â Â Â Â Female         2,518,600
4  Â Â Â Â Â Â Â Â Sex ratio (males per 100 females)              94.1

  Alabama!!Percent Alaska!!Estimate Alaska!!Percent Arizona!!Estimate  \
0              NaN              NaN             NaN               NaN
1        4,887,871          737,438         737,438         7,171,646
2            48.5%          382,952           51.9%         3,565,129
3            51.5%          354,486           48.1%         3,606,517
4              (X)            108.0             (X)              98.9

  Arizona!!Percent Arkansas!!Estimate Arkansas!!Percent California!!Estimate  \
0              NaN                NaN               NaN                  NaN
1        7,171,646          3,013,825         3,013,825           39,557,045
2            49.7%          1,476,680             49.0%           19,673,553
3            50.3%          1,537,145             51.0%           19,883,492
4              (X)               96.1               (X)                 98.9

   ... Washington!!Estimate Washington!!Percent West Virginia!!Estimate  \
0  ...                  NaN                 NaN                     NaN
1  ...            7,535,591           7,535,591               1,805,832
2  ...            3,766,859               50.0%                 894,657
3  ...            3,768,732               50.0%                 911,175
4  ...                100.0                 (X)                    98.2

  West Virginia!!Percent Wisconsin!!Estimate Wisconsin!!Percent  \
0                    NaN                 NaN                NaN
1              1,805,832           5,813,568          5,813,568
2                  49.5%           2,891,282              49.7%
3                  50.5%           2,922,286              50.3%
4                    (X)                98.9                (X)

  Wyoming!!Estimate Wyoming!!Percent Puerto Rico!!Estimate  \
0               NaN              NaN                   NaN
1           577,737          577,737             3,195,153
2           292,619            50.6%             1,520,415
3           285,118            49.4%             1,674,738
4             102.6              (X)                  90.8

  Puerto Rico!!Percent
0                  NaN
1            3,195,153
2                47.6%
3                52.4%
4                  (X)

[5 rows x 105 columns]

In [15]:
import pandas as pd


state_data = []


for column in enrichment_df.columns:
    if "!!Estimate" in column:
        state_name = column.split("!!")[0]

        value = enrichment_df[column][1]  
        if pd.notna(value):  
            state_data.append({"State": state_name, "Population Estimate": value})


transformed_df = pd.DataFrame(state_data)


print(transformed_df.head())

        State Population Estimate
0     Alabama           4,887,871
1      Alaska             737,438
2     Arizona           7,171,646
3    Arkansas           3,013,825
4  California          39,557,045

In [17]:

merged_df = pd.merge(super_covid_df, transformed_df, left_on='State_x', right_on='State', how='left', suffixes=('_covid', '_pop'))


print(merged_df.head())

   countyFIPS    County Name_x State_x  StateFIPS_x  2020-01-22_x  \
0        1001  Autauga County       AL            1             0
1        1003  Baldwin County       AL            1             0
2        1005  Barbour County       AL            1             0
3        1007     Bibb County       AL            1             0
4        1009   Blount County       AL            1             0

   2020-01-23_x  2020-01-24_x  2020-01-25_x  2020-01-26_x  2020-01-27_x  ...  \
0             0             0             0             0             0  ...
1             0             0             0             0             0  ...
2             0             0             0             0             0  ...
3             0             0             0             0             0  ...
4             0             0             0             0             0  ...

   2023-07-19_y  2023-07-20_y  2023-07-21_y  2023-07-22_y  2023-07-23_y  \
0           235           235           235           235           235
1           731           731           731           731           731
2           104           104           104           104           104
3           111           111           111           111           111
4           261           261           261           261           261

      County Name  State_covid  population  State_pop  Population Estimate
0  Autauga County           AL       55869        NaN                  NaN
1  Baldwin County           AL      223234        NaN                  NaN
2  Barbour County           AL       24686        NaN                  NaN
3     Bibb County           AL       22394        NaN                  NaN
4   Blount County           AL       57826        NaN                  NaN

[5 rows x 2542 columns]

In [18]:
merged_df.head()

,countyFIPS,County Name_x,State_x,StateFIPS_x,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,2023-07-19_y,2023-07-20_y,2023-07-21_y,2023-07-22_y,2023-07-23_y,County Name,State_covid,population,State_pop,Population Estimate
0,1001,Autauga County,AL,1,0,0,0,0,0,0,...,235,235,235,235,235,Autauga County,AL,55869,NaN,NaN
1,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,731,731,731,731,731,Baldwin County,AL,223234,NaN,NaN
2,1005,Barbour County,AL,1,0,0,0,0,0,0,...,104,104,104,104,104,Barbour County,AL,24686,NaN,NaN
3,1007,Bibb County,AL,1,0,0,0,0,0,0,...,111,111,111,111,111,Bibb County,AL,22394,NaN,NaN
4,1009,Blount County,AL,1,0,0,0,0,0,0,...,261,261,261,261,261,Blount County,AL,57826,NaN,NaN